version: "3.7"
# https://docs.docker.com/docker-for-mac/osxfs/
services:
  my_service:
    container_name: my-service
    build: .
    entrypoint: bundle
    command: exec server.rb
    volumes:
      - cardbinder_bundle:/usr/local/bundle:cached
    ports:
      - 50052:50052

  bundle:
    build: .
    entrypoint: bundle
    command: check
    volumes:
      - cardbinder_bundle:/usr/local/bundle:cached

  rspec:
    build: .
    entrypoint: bundle
    command: exec rspec --version
    volumes:
      - cardbinder_bundle:/usr/local/bundle:cached

  protoc:
    build: .
    entrypoint: bundle
    command: |
      exec grpc_tools_ruby_protoc
      -I ../protos --ruby_out=./lib --grpc_out=./lib ../protos/my_service.proto
    volumes:
      - cardbinder_bundle:/usr/local/bundle:cached
      - ../protos:/usr/src/protos

volumes:
  cardbinder_bundle:
    external: true

networks:
  default:
    external:
      name: cardbinder_default
